.libPaths( c(paste0(data.path,"R_Libs"), .libPaths())) 
#install.packages("/opt/packages/gurobi900/linux64/R/gurobi_9.0-0_R_3.6.1.tar.gz", repos = NULL)
#install.packages("/afs/andrew.cmu.edu/usr8/mbruchon/bin/gurobi902/linux64/R/gurobi_9.0-2_R_3.6.1.tar.gz", repos = NULL)
#install.packages(c("Matrix","Rcpp","colorspace","plyr","lubridate","kohonen","MASS","scales","lazyeval","tibble","png","glue","tidyselect","backports","dig","deldir","yaml","here","Matrix","matrixStats","data.table","xts","plyr","lubridate","scales","dplyr","fields","lattice","FNN","splitstackshape","fasttime","ggmap","ggplot2"))
#devtools::install("U:\\h3forr-master\\h3forr-master")
library(yaml)
library(here)
library(Matrix)
library(matrixStats)
library(data.table)
library(gurobi)
library(xts)
library(plyr)
library(lubridate)
library(scales)
library(dplyr)
library(fields)
library(lattice)
library(FNN)
library(splitstackshape)
library(fasttime)
library(stringr)
load(paste0(data.path,"Inputs/workspace.RData"))
cores.available <<- 10